export const ROUTES = {
  LOGIN: "/login",
  CARRERA: "/carrera",
  ADMISION: "/admision",
  CONTACTO: "/contacto",
  //estudiante
  ESTUDIANTE: "/estudiante",
  DASHBOARD: "/estudiante/dashboard",
  MATERIA: "/estudiante/materia",
  MATERIADETALLE: "/estudiante/materiadetalle/:id",
  PROYECTO: "/estudiante/proyecto",
  COLABORACION: "/estudiante/colaboracion",
  COLABORACIONDETALLE: "/estudiante/colaboraciones/:id",
  NOTIFICACION: "/estudiante/notificacion",
  TAREAPENDIENTE: "/estudiante/tareapendiente",
  PIZARRA: "/estudiante/pizarra",
  EXCALIDRAW: "/estudiante/excalidraw",
  CALENDARIOU: "/estudiante/calendario",
  //admin
  ADMIN: "/admin",
  DASHBOARDADMIN: "/admin/dashboard",
  DIRECTOCARRERA: "/admin/directo-carrera",
  DOCENTE: "/admin/docente",
  FACULTAD: "/admin/facultad",
  CARRERA: "/admin/carrera",
  SEMESTRE: "/admin/semestre",
  MATERIAS: "/admin/materias",
  HORARIO: "/admin/horario",
  USUARIO: "/admin/usuario",
  GENERAL: "/admin/general",
  //Vista usuario
  PRINCIPAL: "/",
  HOME: "/home",
  CARACTERISTICAS: "/caracteristicas",
  PLATAFORMAS: "/plataformas",
  CENTROAYUDA: "/centroAyuda",
  CONTACTO: "/contacto",
  //Docente
  DOCENTES: "/docente", 
  DASHBOARDDOCENTE: "/docente/dashboard", 
  MISMATERIAS: "/docente/materias", 
  ENTREGAS: "/docente/entregas", 
  REVISION: "/docente/revision",        
  RUBRICAS: "/docente/rubricas",
  CALENDARIODOC: "/docente/calendario",
  EVENTOS: "/docente/eventos",                    
  TAREAS: "/docente/tareas",
  NOTIFICACIONESDOC: "/docente/notificaciones",
  PLAGIO: "/docente/plagio",                  
  COLABORACIONES: "/docente/colaboracion",        
  HORARIODOC: "/docente/horario",
  RECURSOS: "/docente/recursos",                    
  PIZARRADOC: "/docente/pizarra",
  EXCALIDRAWDOC: "/docente/excalidraw",
  
  //Director de Carrera
  DIRECTOR: "/director",
  DASHBOARDDI: "/director/dashboard",
  REPORTESDI: "/director/reportes",
  MISMATERIASDI: "/director/materias", 
  ENTREGASDI: "/director/entregas", 
  REVISIONDI: "/director/revision",        
  RUBRICASDI: "/director/rubricas",
  CALENDARIODI: "/director/calendario",
  EVENTOSDI: "/director/eventos",                    
  TAREASDI: "/director/tareas",
  NOTIFICACIONESDI: "/director/notificaciones",
  PLAGIODI: "/director/plagio",                  
  COLABORACIONESDI: "/director/colaboracion",        
  HORARIODI: "/director/horario",
  RECURSODI: "/director/recursos",                    
  PIZARRADI: "/director/pizarra",
  EXCALIDRAWDI: "/director/excalidraw",
};
